name: Android CI

on:
  push:
    branches: [ "**" ]     # run on ANY branch
  pull_request:
    branches: [ "**" ]     # run on ANY PR target
  workflow_dispatch:       # enables manual run button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        working-directory: mobile-app/MobileApplication
        run: chmod +x gradlew

      - name: Kotlin lint (ktlint)
        working-directory: mobile-app/MobileApplication
        run: |
          curl -sSfL https://github.com/pinterest/ktlint/releases/download/1.3.1/ktlint -o ktlint
          chmod +x ktlint
          ./ktlint "app/src/**/*.kt"


      - name: Build Debug
        working-directory: mobile-app/MobileApplication
        run: ./gradlew assembleDebug

      - name: Run unit tests
        working-directory: mobile-app/MobileApplication
        run: ./gradlew test

      - name: Android Lint
        working-directory: mobile-app/MobileApplication
        run: ./gradlew lint

      - name: Generate JaCoCo report
        working-directory: mobile-app/MobileApplication
        run: ./gradlew jacocoTestReport